// Generated by LiveScript 1.6.0
(function(){
  var window, pushState;
  window = require('./window.ls');
  pushState = function(state, title, page){};
  module.exports = typeof history != 'undefined' && history !== null
    ? history
    : {
      pushState: pushState
    };
}).call(this);
