// Generated by LiveScript 1.6.0
(function(){
  module.exports = function(cb){
    var err;
    try {
      return cb();
    } catch (e$) {
      err = e$;
      return alert(err + "");
    }
  };
}).call(this);
